Reserve the original size of image
terrastruct/d2-obsidian pull request #32
Opened 2023-05-24 14:49 UTC by cs-qyzhang

Images are always scaled to max height even when they are small. It seems that the outer `<svg>` tag d2 generated caused the image to be too large.

Before:

![before](https://github.com/terrastruct/d2-obsidian/assets/37697612/d154f8f3-b0b9-445e-98e2-e419e45db970)

This PR:

![after](https://github.com/terrastruct/d2-obsidian/assets/37697612/b0bd92ff-22ed-4ce9-9d1e-5e1973e6e850)

2023-05-24 17:56 UTC, alixander reviewed
I think the config `Container height` should suffice here. Is this something you tried already? 

There's no way to specify dimensions in D2, so if you use the original size, it might be too small.

2023-05-25 03:24 UTC, cs-qyzhang commented
The `Container height` is a global option, it cannot be set for a single image. Although in d2lang you can set a node's width or height (e.g. `a { width: 10 }`), the image is always scaled to max height even when you do that. The built-in Mermaid of obsidian, the `Obsidian Graphviz` plugin, and the `TikZJax` plugin all display images at their original size, and the image size can be changed by font-size or something else. It would be nice to have consistent behavior with others, especially with built-in mermaid. Even if you can set the image's size by changing d2 node's height or width, it is very tedious to do that for every image and every node.

#### built-in mermaid

````
```mermaid
flowchart
a
```
````

![mermaid](https://github.com/terrastruct/d2-obsidian/assets/37697612/55cbd5f6-c5b3-48d0-8c58-31159b61628f)

#### Obsidian Graphviz

````
```dot
digraph {
  a [
    shape = rect
  ]
} 
```
````

![dot](https://github.com/terrastruct/d2-obsidian/assets/37697612/83bde5a4-62bc-4502-bd50-a405415944b4)

#### TikZJax

````
```tikz
\begin{document}
  \begin{tikzpicture}
    \node[rectangle,draw] {\Large a};
  \end{tikzpicture}
\end{document}
```
````

![tikz](https://github.com/terrastruct/d2-obsidian/assets/37697612/3518932e-5f1d-41cc-9e02-e067d09c3b56)

#### D2

````
```d2
a
```
````

##### before

![图片](https://github.com/terrastruct/d2-obsidian/assets/37697612/5541ede7-bfb8-4ecd-acc5-1444e56678fb)

##### after

![图片](https://github.com/terrastruct/d2-obsidian/assets/37697612/ad821bc6-daf9-4685-ac95-e30b2c7c48d3)

````
```d2
a {
  width: 10
  height: 10
}
```
````

##### before

![图片](https://github.com/terrastruct/d2-obsidian/assets/37697612/8ebaf928-dc69-4491-a7a4-6753b12e11d1)

##### after

![图片](https://github.com/terrastruct/d2-obsidian/assets/37697612/f0ce4aad-ae72-44d2-99d9-9418774711ef)

````
```d2
a {
  style.font-size: 100
}
```
````

##### before

![图片](https://github.com/terrastruct/d2-obsidian/assets/37697612/53792150-f1ff-44e1-8ac3-cbb9c9c4a22e)

##### after

![图片](https://github.com/terrastruct/d2-obsidian/assets/37697612/91b53b40-27ff-4719-8151-e8e0f3284eeb)

2023-08-24 23:47 UTC, MadSci356 commented
Hey @alixander, 

Please merge this into main because @cs-qyzhang 's fixes indeed work. It auto-sizes the diagrams, super useful!

I have tried it locally. Results attached, see where the **"More Text After Diagram"** after each chart. In the current version, it's way too large.

Without this fix, this plugin is practically unusable, as it takes up the _whole_ page for every diagram! Sometimes, it's useful, but that's only the case sometimes. Especially if you want diagrams in between your notes.

### First Screenshot: Before

> ![Before broken](https://github.com/terrastruct/d2-obsidian/assets/5410205/9a604ef9-09a1-4669-b282-e57f2326f484)


### Second Screenshot: Fixed, compiling from this PR
> ![Fixed Diagram Size](https://github.com/terrastruct/d2-obsidian/assets/5410205/fccff720-497c-4061-be1f-67768210ada5)

2023-08-25 01:32 UTC, MadSci356 commented
@cs-qyzhang  Please update this PR so it's not out of date with the base branch.

2023-08-25 17:53 UTC, alixander commented
looks like CI fails due to some typescript

2023-08-28 12:47 UTC, cs-qyzhang commented
Fixed.

2023-11-25 14:09 UTC, alex-roc commented
Hi, any update on this? the problem still persist at this day.

2023-11-27 18:09 UTC, gavin-ts requested changes
Tested and this works. We can add `--scale=1` to the d2 command, and then this won't have to reach into the inner SVG element.

```diff
diff --git a/src/processor.ts b/src/processor.ts
index a51645a..6975027 100644
--- a/src/processor.ts
+++ b/src/processor.ts
@@ -194,6 +194,7 @@ export class D2Processor {
       `--pad=${this.plugin.settings.pad}`,
       `--sketch=${this.plugin.settings.sketch}`,
       "--bundle=false",
+      "--scale=1",
     ];
     const cmd = args.join(" ");
     const child = exec(cmd, options);
```

2023-11-27 18:09 UTC, gavin-ts commented on src/processor.ts
> +    const svgEl = svg!.firstElementChild!.firstElementChild as HTMLElement;
```suggestion
    const svgEl = svg.documentElement;
```

2023-11-28 22:42 UTC, merged

2023-11-28 22:51 UTC, gavin-ts commented
note: pushed signed changes rebased on master, added PR to automatically check for signed commits going forwards #41